### ISSUE TITLE
Bug: incorrect column name in CXGN::Phenome::Locus `new_with_locusname` query

### ISSUE THREAD

**Issue by dwaring87** [solgenomics/Phenome#11]
https://github.com/solgenomics/Phenome/blob/fdd9e7ad7725ffa733b72859342fb130bd72384b/lib/CXGN/Phenome/Locus.pm#L131

This query for the `new_with_locusname` function references the non-existent `locus` column which should be `locus_name`:

`SELECT locus_id FROM phenome.locus WHERE locus_name ilike ? and obsolete = ?`

This is used by the `view_by_name` function in the SGN::Controller::Locus controller.

**Comment by nmenda** [comment]
there is a column 'locus' in the phenome.locus table. It is meant for storing the genome locus name, which is usually the gene model ID and should be unique. The locus_name field might not be unique.

https://github.com/solgenomics/Phenome/blob/fdd9e7ad7725ffa733b72859342fb130bd72384b/lib/CXGN/Phenome/Locus.pm#L120

**Comment by dwaring87** [comment]
Yep, I see it now.  In our database we have locus_name set but the locus column is NULL for all of the loci.  I guess this is just a bug in the way we're storing our data then.  The locus view by name URL should work if we set the locus column in our data to match the locus_name.

**Comment by nmenda** [comment]
at least in solgenomics we use the locus field for linking to jbrowse, so if your locus_name field is not a gene model ID, and you will have in the future gene models in jbrowse, you may need later on to update locus.locus to the gene model ID to match the genome annotation gff file.
